name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Archive release artifact
        uses: actions/upload-artifact@v4
        with:
          name: VetToolByCrew-arm64-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

      - name: Rename APK for release
        run: |
          mkdir -p dist
          cp build/app/outputs/flutter-apk/app-release.apk dist/VetToolByCrew.apk

      - name: Upload renamed APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: VetToolByCrew-apk
          path: dist/VetToolByCrew.apk
          if-no-files-found: error

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/VetToolByCrew.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
