name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Archive release artifact
        uses: actions/upload-artifact@v4
        with:
          name: VetToolByCrew-arm64-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

      - name: Rename APK for release
        run: |
          mkdir -p dist
          cp build/app/outputs/flutter-apk/app-release.apk dist/VetToolByCrew.apk

      - name: Upload renamed APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: VetToolByCrew-apk
          path: dist/VetToolByCrew.apk
          if-no-files-found: error

      - name: Publish GitHub Release
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/VetToolByCrew.apk
          artifactContentType: application/vnd.android.package-archive
          tag: latest
          name: Vet Tool by Crew (latest)
          body: |
            Automated build of Vet Tool by Crew.
            This release is refreshed whenever the build workflow runs.
          allowUpdates: true
